spring.application.name=sistema-guias-despacho

# --- PUERTO DEL SERVIDOR ---
server.port=8080

# --- BASE DE DATOS (H2 para pruebas rapidas locales) ---
spring.datasource.url=jdbc:h2:mem:guiasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# --- AZURE AD B2C (IDaaS) ---
# URL del tenant configurado por tu compañera en Azure
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/69f25d70-e9e4-44a7-99e9-ce5112f77ddd/v2.0

# --- AWS S3 ---
# Aqui pondremos el nombre del bucket una vez creado en AWS Academy
aws.s3.bucket-name=sistema-guias-despacho-renemaria-sumativa2
aws.region=us-east-1 